name: Metrics Isocalendar

on:
# Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch: # Allows manual triggering
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: GitHub Metrics Isocalender
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg #metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""  # Disable base content (e.g., no profile header)
          config_timezone: America/Chicago
          plugin_isocalendar: yes
          #Optional: Uncomment to show full year
          #plugin_isocalendar_duration: full-year
